version: '3'

services:
  web:
    build: .
    ports:
      - ${HOST_PORT}:80
    environment:
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    networks:
      - proxy

networks:
  proxy:
    external: true
