version: '3.1'

services:

  redmine:
    image: arm64v8/redmine
    restart: always
    ports:
      - ${VIRTUAL_PORT}:3000
    environment:
      REDMINE_DB_POSTGRES: ${REDMINE_DB_POSTGRES}
      REDMINE_DB_PORT: ${REDMINE_DB_PORT}
      REDMINE_DB_DATABASE: ${REDMINE_DB_DATABASE}
      REDMINE_DB_USERNAME: ${REDMINE_DB_USERNAME}
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD}
      REDMINE_SECRET_KEY_BASE: ${REDMINE_SECRET_KEY_BASE}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      REDMINE_SMTP_SERVER: ${VIRTUAL_HOST}
      REDMINE_SMTP_PORT: ${VIRTUAL_HOST}
      REDMINE_SMTP_DOMAIN: ${VIRTUAL_HOST}
      REDMINE_SMTP_USER: ${VIRTUAL_HOST}
      REDMINE_SMTP_PASSWORD: ${VIRTUAL_HOST}
    volumes:
      - redmine-data:/usr/src/redmine/files
    networks:
      - proxy

volumes:
  redmine-data:

networks:
  proxy:
    external: true
