version: '2'
services:
  keycloak:
    container_name: keycloak
    restart: unless-stopped
    image: docker.io/bitnami/keycloak:21
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_MANAGEMENT_PASSWORD: ${KEYCLOAK_MANAGEMENT_PASSWORD}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: ${KEYCLOAK_DATABASE_HOST}
      KEYCLOAK_DATABASE_NAME: ${KEYCLOAK_DATABASE_NAME}
      KEYCLOAK_DATABASE_USER: ${KEYCLOAK_DATABASE_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      KEYCLOAK_JDBC_PARAMS: sslmode=verify-full&connectTimeout=30000
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_HTTPS_PORT: 8443
      KEYCLOAK_ENABLE_HTTPS: true
      KEYCLOAK_HTTPS_CERTIFICATE_FILE: /opt/bitnami/keycloak/certs/${VIRTUAL_HOST}.crt
      KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE: /opt/bitnami/keycloak/certs/${VIRTUAL_HOST}.key
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PROTO: https
      VIRTUAL_PORT: 8443
    volumes:
      - custom-themes:/opt/bitnami/keycloak/themes/custom-themes
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - proxy
volumes:
  custom-themes:

networks:
  proxy:
    external: true

