version: '2'
services:
  keycloak:
    container_name: keycloak
    restart: unless-stopped
    image: bitnami/keycloak:latest
    #command: start-dev
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_MANAGEMENT_PASSWORD: ${KEYCLOAK_MANAGEMENT_PASSWORD}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: ${KEYCLOAK_DATABASE_HOST}
      KEYCLOAK_DATABASE_NAME: ${KEYCLOAK_DATABASE_NAME}
      KEYCLOAK_DATABASE_USER: ${KEYCLOAK_DATABASE_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      KEYCLOAK_JDBC_PARAMS: connectTimeout=30000
      KEYCLOAK_HTTP_PORT: 8080
      #KEYCLOAK_HTTPS_PORT: 8443
      KEYCLOAK_ENABLE_HTTPS: false
      #KEYCLOAK_HTTPS_USE_PEM: true
      #KEYCLOAK_HTTPS_CERTIFICATE_FILE: /opt/bitnami/keycloak/certs/cert.pem
      #KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE: /opt/bitnami/keycloak/certs/key.pem
      #KEYCLOAK_HTTPS_TRUST_STORE_FILE: /opt/bitnami/keycloak/certs/truststore.jks
      #KEYCLOAK_HTTPS_KEY_STORE_FILE: /opt/bitnami/keycloak/certs/keystore.jks
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      #VIRTUAL_PROTO: https
      VIRTUAL_PORT: 8080
      #KEYCLOAK_EXTRA_ARGS: "start-dev"
    volumes:
      - custom-themes:/opt/bitnami/keycloak/themes/custom-themes
      #- /root/server/proxy/data/certs/${VIRTUAL_HOST}:/opt/bitnami/keycloak/certs
    ports:
      - "8080:8080"
      #- "8443:8443"
    networks:
      - proxy
volumes:
  custom-themes:

networks:
  proxy:
    external: true

