version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: unless-stopped
    expose:
      - "80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
        #      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: True
        #      PGADMIN_CONFIG_LOGIN_BANNER: "Authorised users only!"
        #PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
        #PGADMIN_ENABLE_TLS: True
        #VIRTUAL_PROTO: http
      VIRTUAL_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
        #- /root/server/proxy/data/certs/server.cert:/certs/server.cert
        #- /root/server/proxy/data/certs/server.key:/certs/server.key
    networks:
      - proxy

volumes:
  pgadmin-data:

networks:
  proxy:
    external: true

