apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres-namespace
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_USER: ${POSTGRES_USER} 